profile=high-quality

#video
vo=gpu-next
gpu-api=auto
hwdec=auto

#audio
ao=pulse

#sync
video-sync=display-resample
video-sync-max-video-change=0.01
interpolation=yes

#misc
keep-open=yes
save-position-on-quit=yes
autofit-larger=80%x80%

[SDR]
profile-desc=SDR
profile-cond=get("video-params/gamma") == "bt.1886" and not get("inverse-tone-mapping")
profile-restore=copy
target-colorspace-hint=no

[HDR]
profile-desc=HDR
profile-cond=get("video-params/max-luma") > 203
profile-restore=copy
target-colorspace-hint=auto
target-colorspace-hint-mode=target
blend-subtitles=no
deband=no
vf=""

[HDR Passthrough]
profile-desc=HDR Passthrough
profile-cond=get("video-params/max-luma") > 203 and get("video-target-params/max-luma") > 203
profile-restore=copy
icc-profile=""
icc-profile-auto=no
target-colorspace-hint=auto
target-colorspace-hint-mode=target
inverse-tone-mapping=no
target-prim=auto
target-trc=auto
target-peak=auto
target-contrast=auto

[Downmix_Audio_5_1]
profile-cond=get("audio-params/channel-count") >= 5 and get("audio-params/channel-count") < 7
profile-restore=copy-equal
volume-max=200
af=lavfi="lowpass=c=LFE:f=120,volume=1.6,pan=stereo|FL=0.5*FC+0.707*FL+0.707*BL+0.5*LFE|FR=0.5*FC+0.707*FR+0.707*BR+0.5*LFE"

[Downmix_Audio_7_1]
profile-cond=get("audio-params/channel-count") >= 7
profile-restore=copy-equal
volume-max=200
af=lavfi="lowpass=c=LFE:f=120,volume=1.6,pan=stereo|FL=0.5*FC+0.3*FLC+0.3*FL+0.3*BL+0.3*SL+0.5*LFE|FR=0.5*FC+0.3*FRC+0.3*FR+0.3*BR+0.3*SR+0.5*LFE"
